import type { Product } from '../types';

export const defaultProducts: Product[] = [
  // Agent products
  {
    id: 'manus',
    name: 'Manus',
    url: 'https://www.manus.im',
    selector: 'textarea',
    submitSelector: 'button[type="submit"]',
    enabled: false,
  },
  {
    id: 'anygen',
    name: 'Anygen',
    url: 'https://www.anygen.io/',
    selector: 'textarea',
    submitSelector: 'button[aria-label*="send" i], button[aria-label*="发送" i]',
    enabled: false,
  },
  {
    id: 'coze',
    name: 'Coze',
    url: 'https://www.coze.cn',
    selector: 'textarea',
    submitSelector: 'button[type="submit"]',
    enabled: false,
  },
  {
    id: 'minimax',
    name: 'Minimax',
    url: 'https://agent.minimaxi.com/',
    selector: 'textarea',
    submitSelector: 'button[aria-label*="send" i]',
    enabled: false,
  },

  // Chat products
  {
    id: 'chatgpt',
    name: 'ChatGPT',
    url: 'https://chatgpt.com',
    selector: '#prompt-textarea',
    submitSelector: 'button[data-testid="send-button"]',
    enabled: false,
  },
  {
    id: 'claude',
    name: 'Claude',
    url: 'https://claude.ai/new',
    selector: 'div[contenteditable="true"][data-placeholder]',
    submitSelector: 'button[aria-label="Send message"]',
    enabled: false,
  },
  {
    id: 'perplexity',
    name: 'Perplexity',
    url: 'https://www.perplexity.ai',
    selector: 'textarea',
    submitSelector: 'button[aria-label*="submit" i]',
    enabled: false,
  },
  {
    id: 'gemini',
    name: 'Gemini',
    url: 'https://gemini.google.com',
    selector: 'textarea',
    submitSelector: 'button[aria-label*="send" i]',
    enabled: false,
  },
  {
    id: 'qianwen',
    name: 'Tongyi Qwen',
    url: 'https://www.qianwen.com/',
    selector: 'textarea',
    submitSelector: 'button[type="submit"]',
    enabled: false,
  },
  {
    id: 'doubao',
    name: 'Doubao',
    url: 'https://www.doubao.com',
    selector: 'textarea',
    submitSelector: 'button[aria-label*="发送" i]',
    enabled: false,
  },
  {
    id: 'yiyan',
    name: 'ERNIE Bot',
    url: 'https://yiyan.baidu.com',
    selector: 'textarea',
    submitSelector: 'button[type="submit"]',
    enabled: false,
  },
  {
    id: 'kimi',
    name: 'Kimi',
    url: 'https://kimi.moonshot.cn',
    selector: 'textarea',
    submitSelector: 'button[type="submit"]',
    enabled: false,
  },
  {
    id: 'genspark',
    name: 'Genspark',
    url: 'https://www.genspark.ai',
    selector: 'textarea',
    submitSelector: 'button[type="submit"]',
    enabled: false,
  },
  {
    id: 'autoglm',
    name: 'AutoGLM',
    url: 'https://chatglm.cn',
    selector: 'textarea',
    submitSelector: 'button[aria-label*="send" i]',
    enabled: false,
  },
  {
    id: 'metaso',
    name: 'Metaso',
    url: 'https://metaso.cn',
    selector: 'textarea',
    submitSelector: 'button[type="submit"]',
    enabled: false,
  },
  {
    id: 'grok',
    name: 'Grok',
    url: 'https://x.com/i/grok',
    selector: 'textarea',
    submitSelector: 'button[data-testid="send-button"]',
    enabled: false,
  },
  {
    id: 'zhipu',
    name: 'ChatGLM',
    url: 'https://chatglm.cn',
    selector: 'textarea',
    submitSelector: 'button[aria-label*="发送" i]',
    enabled: false,
  },
];
